### PR TITLE
Add cli

### PR DESCRIPTION
**Pull request by ChristophB**
The interface is not usable yet. "Fat" JAR packaging must be configured.

### CODE REVIEW

**Comment by KonradHoeffner** [comment]
Don't we need a manifest or something to indicate the main class?

**Comment by ChristophB** [comment]
This is not required for the `appassembler-maven-plugin`. The plugin creates executable binary files on `mvn package`.

**Comment by ChristophB** [comment]
I removed the `appassembler-maven-plugin` because it does not add much value (JRE is still required).
Insteat, I added the `maven-shade-plugin` to build a fat and executable JAR with main class listed in the manifest.

**Review by KonradHoeffner — COMMENTED** [review]
After looking at a few other Java applications, namely [tarql](https://github.com/tarql/tarql/blob/master/pom.xml) and [Protege](https://github.com/protegeproject/protege/blob/master/protege-desktop/pom.xml), I didn't see the maven-exec-java plugin used so maybe that commit from me was unnecessary, however I find it useful for testing.
I found this post about standard Java packaging useful as well: <https://stackoverflow.com/a/75211416/398963>. Apparently if you bundle the JRE with the Java application you can also reduce its size using jlink, I'm not sure how the shade plugin fits into that.

**Comment by ChristophB** [comment]
I'd leave the `exec-maven` plugin in place. It is just another way to use SMOG and does not add too much overhead.

**Pull request merged**
